package biz.pixelperfectstudios.personaspeak.personas

import org.junit.Test
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import kotlin.io.path.inputStream
import kotlin.io.path.listDirectoryEntries
import kotlin.io.path.nameWithoutExtension
import kotlin.io.path.readText
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Pins the Kotlin prompt builder to the Python reference implementation.
 * Fixtures in tests/golden/ are generated by desktop/personaspeak.py —
 * if this test fails, either the port drifted or the schema changed
 * without regenerating fixtures (see AGENTS.md rule 2).
 */
class PromptBuilderGoldenTest {

    // Test working dir is the module dir (android/core-personas) → repo root is ../..
    private val repoRoot: Path = Paths.get("../..").toAbsolutePath().normalize()
    private val personasDir = repoRoot.resolve("personas")
    private val goldenDir = repoRoot.resolve("tests/golden")

    @Test
    fun `kotlin prompts are byte-identical to the python reference`() {
        val personaFiles = personasDir.listDirectoryEntries("*.yaml").sortedBy { it.fileName }
        assertTrue(personaFiles.isNotEmpty(), "no personas found at $personasDir")

        for (file in personaFiles) {
            val golden = goldenDir.resolve("${file.nameWithoutExtension}.prompt.txt")
            assertTrue(
                Files.exists(golden),
                "missing golden fixture for ${file.fileName} — regenerate with the python reference",
            )
            val persona = file.inputStream().use { Persona.fromYaml(it) }
            assertEquals(
                golden.readText(),
                PromptBuilder.build(persona),
                "prompt drift for ${file.fileName}",
            )
        }
    }

    @Test
    fun `kotlin suggestion prompts are byte-identical to the python reference`() {
        val personaFiles = personasDir.listDirectoryEntries("*.yaml").sortedBy { it.fileName }
        assertTrue(personaFiles.isNotEmpty(), "no personas found at $personasDir")

        for (file in personaFiles) {
            val golden = goldenDir.resolve("${file.nameWithoutExtension}.suggest.txt")
            assertTrue(
                Files.exists(golden),
                "missing suggestion golden for ${file.fileName} — regenerate with " +
                    "`python3 desktop/personaspeak.py --suggest --as ${file.nameWithoutExtension} " +
                    "| perl -pe 'chomp if eof'` (store without the CLI's trailing newline)",
            )
            val persona = file.inputStream().use { Persona.fromYaml(it) }
            // Canonical inputs shared with the CLI defaults: sender "Sam", app
            // "Messages", count 3, no mood — keep both sides in lockstep.
            assertEquals(
                golden.readText(),
                PromptBuilder.buildSuggestionPrompt(
                    persona = persona,
                    incoming = IncomingMessageContext(
                        sender = "Sam",
                        appLabel = "Messages",
                        text = "unused by the prompt — travels as the user turn",
                    ),
                    count = 3,
                ),
                "suggestion prompt drift for ${file.fileName}",
            )
        }
    }
}
